//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class compendium {
    
    private compendiumItem[] itemField;
    
    private compendiumRace[] raceField;
    
    private compendiumClass[] classField;
    
    private compendiumFeat[] featField;
    
    private compendiumBackground[] backgroundField;
    
    private compendiumSpell[] spellField;
    
    private compendiumMonster[] monsterField;
    
    private byte versionField;
    
    private string auto_indentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public compendiumItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("race")]
    public compendiumRace[] race {
        get {
            return this.raceField;
        }
        set {
            this.raceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("class")]
    public compendiumClass[] @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("feat")]
    public compendiumFeat[] feat {
        get {
            return this.featField;
        }
        set {
            this.featField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("background")]
    public compendiumBackground[] background {
        get {
            return this.backgroundField;
        }
        set {
            this.backgroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("spell")]
    public compendiumSpell[] spell {
        get {
            return this.spellField;
        }
        set {
            this.spellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("monster")]
    public compendiumMonster[] monster {
        get {
            return this.monsterField;
        }
        set {
            this.monsterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string auto_indent {
        get {
            return this.auto_indentField;
        }
        set {
            this.auto_indentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumItem {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ac", typeof(int))]
    [System.Xml.Serialization.XmlElementAttribute("detail", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dmg1", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dmg2", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("dmgType", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("magic", typeof(int))]
    [System.Xml.Serialization.XmlElementAttribute("modifier", typeof(compendiumItemModifier))]
    [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("property", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("range", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("roll", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("stealth", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("strength", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("type", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("value", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("weight", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumItemModifier {
    
    private string categoryField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    ac,
    
    /// <remarks/>
    detail,
    
    /// <remarks/>
    dmg1,
    
    /// <remarks/>
    dmg2,
    
    /// <remarks/>
    dmgType,
    
    /// <remarks/>
    magic,
    
    /// <remarks/>
    modifier,
    
    /// <remarks/>
    name,
    
    /// <remarks/>
    property,
    
    /// <remarks/>
    range,
    
    /// <remarks/>
    roll,
    
    /// <remarks/>
    stealth,
    
    /// <remarks/>
    strength,
    
    /// <remarks/>
    text,
    
    /// <remarks/>
    type,
    
    /// <remarks/>
    value,
    
    /// <remarks/>
    weight,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumRace {
    
    private string nameField;
    
    private string sizeField;
    
    private byte speedField;
    
    private string abilityField;
    
    private string spellAbilityField;
    
    private string proficiencyField;
    
    private compendiumRaceTrait[] traitField;
    
    private compendiumRaceModifier modifierField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public byte speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    public string ability {
        get {
            return this.abilityField;
        }
        set {
            this.abilityField = value;
        }
    }
    
    /// <remarks/>
    public string spellAbility {
        get {
            return this.spellAbilityField;
        }
        set {
            this.spellAbilityField = value;
        }
    }
    
    /// <remarks/>
    public string proficiency {
        get {
            return this.proficiencyField;
        }
        set {
            this.proficiencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("trait")]
    public compendiumRaceTrait[] trait {
        get {
            return this.traitField;
        }
        set {
            this.traitField = value;
        }
    }
    
    /// <remarks/>
    public compendiumRaceModifier modifier {
        get {
            return this.modifierField;
        }
        set {
            this.modifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumRaceTrait {
    
    private string nameField;
    
    private string[] textField;
    
    private string specialField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string special {
        get {
            return this.specialField;
        }
        set {
            this.specialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumRaceModifier {
    
    private string categoryField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumClass {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("armor", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("autolevel", typeof(compendiumClassAutolevel))]
    [System.Xml.Serialization.XmlElementAttribute("hd", typeof(int))]
    [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("numSkills", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("proficiency", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("spellAbility", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("tools", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("wealth", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("weapons", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumClassAutolevel {
    
    private compendiumClassAutolevelSlots slotsField;
    
    private compendiumClassAutolevelFeature featureField;
    
    private string[] textField;
    
    private int levelField;
    
    private string scoreImprovementField;
    
    /// <remarks/>
    public compendiumClassAutolevelSlots slots {
        get {
            return this.slotsField;
        }
        set {
            this.slotsField = value;
        }
    }
    
    /// <remarks/>
    public compendiumClassAutolevelFeature feature {
        get {
            return this.featureField;
        }
        set {
            this.featureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scoreImprovement {
        get {
            return this.scoreImprovementField;
        }
        set {
            this.scoreImprovementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumClassAutolevelSlots {
    
    private string optionalField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumClassAutolevelFeature {
    
    private string nameField;
    
    private string[] textField;
    
    private string proficiencyField;
    
    private compendiumClassAutolevelFeatureModifier[] modifierField;
    
    private string specialField;
    
    private string optionalField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string proficiency {
        get {
            return this.proficiencyField;
        }
        set {
            this.proficiencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("modifier")]
    public compendiumClassAutolevelFeatureModifier[] modifier {
        get {
            return this.modifierField;
        }
        set {
            this.modifierField = value;
        }
    }
    
    /// <remarks/>
    public string special {
        get {
            return this.specialField;
        }
        set {
            this.specialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumClassAutolevelFeatureModifier {
    
    private string categoryField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    armor,
    
    /// <remarks/>
    autolevel,
    
    /// <remarks/>
    hd,
    
    /// <remarks/>
    name,
    
    /// <remarks/>
    numSkills,
    
    /// <remarks/>
    proficiency,
    
    /// <remarks/>
    spellAbility,
    
    /// <remarks/>
    tools,
    
    /// <remarks/>
    wealth,
    
    /// <remarks/>
    weapons,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumFeat {
    
    private string nameField;
    
    private string prerequisiteField;
    
    private string[] textField;
    
    private string proficiencyField;
    
    private compendiumFeatModifier[] modifierField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string prerequisite {
        get {
            return this.prerequisiteField;
        }
        set {
            this.prerequisiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string proficiency {
        get {
            return this.proficiencyField;
        }
        set {
            this.proficiencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("modifier")]
    public compendiumFeatModifier[] modifier {
        get {
            return this.modifierField;
        }
        set {
            this.modifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumFeatModifier {
    
    private string categoryField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumBackground {
    
    private string nameField;
    
    private string proficiencyField;
    
    private compendiumBackgroundTrait[] traitField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string proficiency {
        get {
            return this.proficiencyField;
        }
        set {
            this.proficiencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("trait")]
    public compendiumBackgroundTrait[] trait {
        get {
            return this.traitField;
        }
        set {
            this.traitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumBackgroundTrait {
    
    private string nameField;
    
    private string[] textField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumSpell {
    
    private string nameField;
    
    private byte levelField;
    
    private string schoolField;
    
    private string ritualField;
    
    private string timeField;
    
    private string rangeField;
    
    private string componentsField;
    
    private string durationField;
    
    private string classesField;
    
    private string[] textField;
    
    private string[] rollField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public byte level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public string school {
        get {
            return this.schoolField;
        }
        set {
            this.schoolField = value;
        }
    }
    
    /// <remarks/>
    public string ritual {
        get {
            return this.ritualField;
        }
        set {
            this.ritualField = value;
        }
    }
    
    /// <remarks/>
    public string time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public string range {
        get {
            return this.rangeField;
        }
        set {
            this.rangeField = value;
        }
    }
    
    /// <remarks/>
    public string components {
        get {
            return this.componentsField;
        }
        set {
            this.componentsField = value;
        }
    }
    
    /// <remarks/>
    public string duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string classes {
        get {
            return this.classesField;
        }
        set {
            this.classesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("roll")]
    public string[] roll {
        get {
            return this.rollField;
        }
        set {
            this.rollField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumMonster {
    
    private string nameField;
    
    private string sizeField;
    
    private string typeField;
    
    private string alignmentField;
    
    private string acField;
    
    private string hpField;
    
    private string speedField;
    
    private byte strField;
    
    private byte dexField;
    
    private byte conField;
    
    private string intField;
    
    private byte wisField;
    
    private string chaField;
    
    private string saveField;
    
    private string skillField;
    
    private string resistField;
    
    private string vulnerableField;
    
    private string immuneField;
    
    private string conditionImmuneField;
    
    private string sensesField;
    
    private byte passiveField;
    
    private string languagesField;
    
    private string crField;
    
    private compendiumMonsterTrait[] traitField;
    
    private compendiumMonsterAction[] actionField;
    
    private compendiumMonsterReaction reactionField;
    
    private compendiumMonsterLegendary[] legendaryField;
    
    private string spellsField;
    
    private string slotsField;
    
    private string environmentField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string alignment {
        get {
            return this.alignmentField;
        }
        set {
            this.alignmentField = value;
        }
    }
    
    /// <remarks/>
    public string ac {
        get {
            return this.acField;
        }
        set {
            this.acField = value;
        }
    }
    
    /// <remarks/>
    public string hp {
        get {
            return this.hpField;
        }
        set {
            this.hpField = value;
        }
    }
    
    /// <remarks/>
    public string speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    public byte str {
        get {
            return this.strField;
        }
        set {
            this.strField = value;
        }
    }
    
    /// <remarks/>
    public byte dex {
        get {
            return this.dexField;
        }
        set {
            this.dexField = value;
        }
    }
    
    /// <remarks/>
    public byte con {
        get {
            return this.conField;
        }
        set {
            this.conField = value;
        }
    }
    
    /// <remarks/>
    public string @int {
        get {
            return this.intField;
        }
        set {
            this.intField = value;
        }
    }
    
    /// <remarks/>
    public byte wis {
        get {
            return this.wisField;
        }
        set {
            this.wisField = value;
        }
    }
    
    /// <remarks/>
    public string cha {
        get {
            return this.chaField;
        }
        set {
            this.chaField = value;
        }
    }
    
    /// <remarks/>
    public string save {
        get {
            return this.saveField;
        }
        set {
            this.saveField = value;
        }
    }
    
    /// <remarks/>
    public string skill {
        get {
            return this.skillField;
        }
        set {
            this.skillField = value;
        }
    }
    
    /// <remarks/>
    public string resist {
        get {
            return this.resistField;
        }
        set {
            this.resistField = value;
        }
    }
    
    /// <remarks/>
    public string vulnerable {
        get {
            return this.vulnerableField;
        }
        set {
            this.vulnerableField = value;
        }
    }
    
    /// <remarks/>
    public string immune {
        get {
            return this.immuneField;
        }
        set {
            this.immuneField = value;
        }
    }
    
    /// <remarks/>
    public string conditionImmune {
        get {
            return this.conditionImmuneField;
        }
        set {
            this.conditionImmuneField = value;
        }
    }
    
    /// <remarks/>
    public string senses {
        get {
            return this.sensesField;
        }
        set {
            this.sensesField = value;
        }
    }
    
    /// <remarks/>
    public byte passive {
        get {
            return this.passiveField;
        }
        set {
            this.passiveField = value;
        }
    }
    
    /// <remarks/>
    public string languages {
        get {
            return this.languagesField;
        }
        set {
            this.languagesField = value;
        }
    }
    
    /// <remarks/>
    public string cr {
        get {
            return this.crField;
        }
        set {
            this.crField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("trait")]
    public compendiumMonsterTrait[] trait {
        get {
            return this.traitField;
        }
        set {
            this.traitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action")]
    public compendiumMonsterAction[] action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    public compendiumMonsterReaction reaction {
        get {
            return this.reactionField;
        }
        set {
            this.reactionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("legendary")]
    public compendiumMonsterLegendary[] legendary {
        get {
            return this.legendaryField;
        }
        set {
            this.legendaryField = value;
        }
    }
    
    /// <remarks/>
    public string spells {
        get {
            return this.spellsField;
        }
        set {
            this.spellsField = value;
        }
    }
    
    /// <remarks/>
    public string slots {
        get {
            return this.slotsField;
        }
        set {
            this.slotsField = value;
        }
    }
    
    /// <remarks/>
    public string environment {
        get {
            return this.environmentField;
        }
        set {
            this.environmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumMonsterTrait {
    
    private string nameField;
    
    private string[] textField;
    
    private string[] attackField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attack")]
    public string[] attack {
        get {
            return this.attackField;
        }
        set {
            this.attackField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumMonsterAction {
    
    private string nameField;
    
    private string[] textField;
    
    private string[] attackField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attack")]
    public string[] attack {
        get {
            return this.attackField;
        }
        set {
            this.attackField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumMonsterReaction {
    
    private string nameField;
    
    private string[] textField;
    
    private string attackField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string attack {
        get {
            return this.attackField;
        }
        set {
            this.attackField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class compendiumMonsterLegendary {
    
    private string nameField;
    
    private string[] textField;
    
    private string[] attackField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("text")]
    public string[] text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attack")]
    public string[] attack {
        get {
            return this.attackField;
        }
        set {
            this.attackField = value;
        }
    }
}
